version: '2'

services:
  backend-golang:
    image: golang-common-packages:latest
    container_name: golang-common-packages
    hostname: golang-common-packages
    ports:
      - "127.0.0.1:4040:3000"
    networks:
      - default
      - template-network

networks:
  default:
    driver: bridge
  template-network:
    external:
      name: template-network