server:
  name: "service-template"
  version: "v1"
  port: 3000
  shutdownTimeout: 0
  heroku: false
  logging: false
  monitoring: false
  https: false

service:
  database:
    onedrive:
      url: "https://graph.microsoft.com/v1.0"
      accessToken: ""
      refreshToken: ""
    dropbox:
      token: ""
    drive:
      apiKey: ""
    sharepoint:
      siteURL: ""
      username: ""
      password: ""
    redis:
      prefix: "bg_"
      password: ""
      host: ""
      db: 0
    mongodb:
      user: ""
      password: ""
      hosts: ""
      db: "service-template"
      options:
        - "test"
        - "retryWrites=true"
    collection:
      document: "document"
      user: "user"
    postgres:
      host: "0.0.0.0"
      port: "5432"
      user: "postgres"
      password: "changeme"
      dbname: "service-template"
  email:
    host: "smtp.gmail.com"
    port: 587
    username: ""
    password: ""
    key: ""
    from: ""
    subject: "Verification code for "
    message: "Your verification code is: "
  newrelic:
    licenseKey: ""
  pgo:
    spaceName: "service-template"
  fluent:
    port: 5160
    host: "fluentd-aggregator"
    prefix: "backend"
    tag: "test"
  kafka:
    hosts:
      - "kafka1:9092"
      - "kafka2:9093"
    partition: 0
  rabbitmq:
    host: "rabbitmq-node-1:5672"
    user: ""
    password: ""
    route: "#"
  mqtt:
    host: "mqtt:1883"
    qos: 0
    prefixPub: "backend-golang-pub_"
    prefixSub: "backend-golang-sub_"

defaultAccount:
  username: "admin"
  password: "12345678x@X"

token:
  accessToken:
    enable: true
    publicKey: "./key/app.rsa.pub"
    privateKey: "./key/app.rsa"
    jwtTimeout: 1
  refreshToken:
    enable: true
    publicKey: "./key/refresh.rsa.pub"
    privateKey: "./key/refresh.rsa"
    jwtTimeout: 24
  otp:
    secretKey: "4S62BZNFXXSZLCRO"
    timeout: 5
